name: java-build_N_deploy-pipeline

pool: Self-Hosted

trigger: none

stages:
  - stage: applicationBuild
    displayName: Application Build and Package Artifacts
    jobs:

      - job: mavenBuild
        displayName: Build with Maven
        steps:

          - task: JavaToolInstaller@1
            displayName: Java Setup
            inputs:
              versionSpec: '21'
              jdkArchitectureOption: 'arm64'
              jdkSourceOption: 'PreInstalled'

          - task: Maven@4
            displayName: Maven Build
            inputs:
              mavenPomFile: '$(System.DefaultWorkingDirectory)/frontend/pom.xml'
              goals: 'clean package'
