name: "Develop Environment Terraform Workflow"

run-name: terraform-workflow-${{ github.run_id }} deploy-by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Run Job'
        required: true
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

jobs:
  terraform-init-plan:
    uses: anurag-vj/devops-cicd-library/.github/workflows/terraform_plan.yaml@main
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    with:
      job_name: 'terraform plan'
      runs_on: 'ubuntu-latest'
      working_directory: './terraform'

  terraform-apply:
    uses: anurag-vj/devops-cicd-library/.github/workflows/terraform_apply.yaml@main
    needs: terraform-init-plan
    if: ${{ github.event.inputs.run_job == 'true' }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    with:
      job_name: 'terraform apply'
      runs_on: 'ubuntu-latest'
      working_directory: './terraform'
